"""Tests for render_markdown — pure string formatter that consumes already-
fetched summaries and returns a markdown string.

render_markdown calls wallclock_work_seconds() / engaged_with_ai_seconds() only
when `umbrella_today` is truthy, and those would hit the network. We monkey-
patch them so the formatter is exercised in isolation.
"""
import os
import time
from datetime import datetime, timezone

import pytest

import aggregate
from aggregate import render_markdown


DAY = datetime(2026, 1, 15, 0, 0, 0, tzinfo=timezone.utc)


@pytest.fixture
def m_wallclock(monkeypatch):
    """Stub out the two helpers render_markdown calls inside umbrella_today."""
    monkeypatch.setattr(aggregate, "wallclock_work_seconds", lambda day: 5400.0)
    monkeypatch.setattr(aggregate, "engaged_with_ai_seconds", lambda day: 1800.0)


# ── minimal / empty inputs ──────────────────────────────────────────────────

def test_render_includes_date_in_title():
    md = render_markdown(DAY, states={}, engagement={}, autonomous={})
    assert "# Тайм-трекер — 2026-01-15" in md


def test_render_with_all_empty_data_does_not_crash():
    md = render_markdown(DAY, states={}, engagement={}, autonomous={})
    # Each section's empty-state marker should appear
    assert "_данных нет — AW не запущен?_" in md
    assert "_диалога не было_" in md
    assert "_автономных задач не запускалось_" in md


def test_render_without_umbrella_omits_projects_section():
    md = render_markdown(DAY, states={}, engagement={}, autonomous={})
    assert "## Работа по проектам" not in md
    assert "## Прочая активность" not in md


def test_render_signature_section_always_present():
    md = render_markdown(DAY, states={}, engagement={}, autonomous={})
    assert "_Generated by `aw-agent-time/scripts/aggregate.py`" in md
    assert "## Как читать" in md


# ── umbrella_today (coding/other) ───────────────────────────────────────────

def test_render_no_keyboard_time_shows_placeholder(monkeypatch):
    # Genuinely no keyboard activity at all → "работы нет".
    monkeypatch.setattr(aggregate, "wallclock_work_seconds", lambda day: 0.0)
    monkeypatch.setattr(aggregate, "engaged_with_ai_seconds", lambda day: 0.0)
    md = render_markdown(
        DAY, states={}, engagement={}, autonomous={},
        umbrella_today={"coding": {}, "other": {}},
    )
    assert "## Работа по проектам" in md
    assert "_сегодня работы нет_" in md
    assert "## Прочая активность" in md
    assert "_прочей активности нет_" in md


def test_render_no_coding_but_keyboard_time_shows_balance(m_wallclock):
    # 1h30m keyboard time, no named project and no "other" → the whole
    # wallclock is unattributed. It must still surface, not be hidden behind
    # "работы нет".
    md = render_markdown(
        DAY, states={}, engagement={}, autonomous={},
        umbrella_today={"coding": {}, "other": {}},
    )
    assert "_сегодня работы нет_" not in md
    assert "**Реальное время за клавиатурой:** 1h30m" in md
    assert "Не атрибутировано: 1h30m" in md


def test_render_coding_projects_sorted_desc_with_totals(m_wallclock):
    umbrella = {
        "coding": {
            "Client A": {"trainer": 3600, "utils": 1800},   # 1h30m total
            "Client B": {"project-b": 600},                      # 10m total
        },
        "other": {},
    }
    md = render_markdown(DAY, states={}, engagement={}, autonomous={},
                         umbrella_today=umbrella)
    # Umbrellas sorted by total desc → Client A before Client B
    client_a_idx = md.index("### Client A — 1h30m")
    client_b_idx = md.index("### Client B — 10m")
    assert client_a_idx < client_b_idx
    # Within an umbrella, projects sorted by seconds desc
    assert "`trainer` — 1h00m" in md
    assert "`utils` — 30m" in md
    assert md.index("`trainer`") < md.index("`utils`")
    # Wall-clock + engaged AI lines (from monkeypatched stubs)
    assert "**Реальное время за клавиатурой:** 1h30m" in md
    assert "**В диалоге с AI:** 30m" in md


def test_render_shows_attribution_quality_and_ambiguity(m_wallclock):
    md = render_markdown(
        DAY,
        states={},
        engagement={},
        autonomous={},
        umbrella_today={"coding": {"OXI": {"oxi-skills": 3600}}, "other": {}},
        attribution={
            "direct": 3600,
            "inferred": 1200,
            "application": 300,
            "unattributed": 300,
            "ambiguous": 600,
            "wallclock": 5400,
        },
    )
    assert "**Качество атрибуции:**" in md
    assert "напрямую 1h00m" in md
    assert "восстановлено 20m" in md
    assert "неоднозначно 10m (11%)" in md


def test_render_other_section_aggregates_and_lists_top(m_wallclock):
    umbrella = {
        "coding": {},
        "other": {
            "Browser": {"Chrome": 7200, "Safari": 1800},   # 2h30m
            "Messages": {"ChatApp": 300},                     # 5m
        },
    }
    md = render_markdown(DAY, states={}, engagement={}, autonomous={},
                         umbrella_today=umbrella)
    # Total = 7200 + 1800 + 300 = 9300s = 2h35m
    assert "**Всего:** 2h35m" in md
    # Sorted desc: Browser (2h30m) before Messages (5m)
    assert md.index("**Browser** — 2h30m") < md.index("**Messages** — 5m")
    # Top-3 inline items inside Browser
    assert "(Chrome 2h00m, Safari 30m)" in md


# ── Layer 1 states ───────────────────────────────────────────────────────────

def test_render_states_lists_active_states_only():
    states = {
        "ACTIVE_EDIT": {"project-c": 1800, "project-a": 600},
        "IDLE": {"chrome": 9999},   # IDLE state should still appear with its own header
    }
    md = render_markdown(DAY, states=states, engagement={}, autonomous={})
    assert "### Активно печатал — 40m" in md          # 1800+600 = 2400s
    assert "`project-c` — 30m" in md
    assert "`project-a` — 10m" in md
    assert "### Не работал — 2h46m" in md             # 9999s


def test_render_states_skips_empty_state_buckets():
    states = {"ACTIVE_EDIT": {"project-c": 600}, "IDLE": {}}
    md = render_markdown(DAY, states=states, engagement={}, autonomous={})
    assert "### Активно печатал" in md
    # Empty state bucket is skipped — no header for it.
    # (Use the header form `### Не работал`, because the literal string
    # "Не работал" also appears in the footer "Как читать" section.)
    assert "### Не работал" not in md


# ── Layer 2 engagement ──────────────────────────────────────────────────────

def test_render_engagement_total_and_items():
    engagement = {("project-c", "claude"): 3600, ("project-a", "codex"): 1800}
    md = render_markdown(DAY, states={}, engagement=engagement, autonomous={})
    # Total = 3600 + 1800 = 5400s = 1h30m
    assert "**Всего в диалоге:** 1h30m" in md
    assert "`project-c` · claude — 1h00m" in md
    assert "`project-a` · codex — 30m" in md
    # Sorted desc — project-c first
    assert md.index("`project-c` · claude") < md.index("`project-a` · codex")


# ── Layer 1b tmux panes ─────────────────────────────────────────────────────

def test_render_panes_grouped_by_session():
    panes = {
        ("dev", "project-c"): 600,
        ("dev", "project-a"): 300,
        ("ops", "deploy"): 120,
    }
    md = render_markdown(DAY, states={}, engagement={}, autonomous={}, panes=panes)
    assert "## Слой 1b — tmux-панели" in md
    # dev session total = 600+300 = 900s = 15m
    assert "### `dev` — 15m" in md
    assert "### `ops` — 2m" in md
    # Within dev, projects sorted desc
    assert md.index("`project-c` — 10m") < md.index("`project-a` — 5m")


def test_render_without_panes_omits_section():
    md = render_markdown(DAY, states={}, engagement={}, autonomous={}, panes=None)
    assert "## Слой 1b" not in md


# ── Layer 2.5 autonomous ────────────────────────────────────────────────────

def test_render_autonomous_total_and_items():
    autonomous = {("project-c", "task-runner"): 7200, ("project-a", "task-runner"): 900}
    md = render_markdown(DAY, states={}, engagement={}, autonomous=autonomous)
    assert "**Всего времени агентов:** 2h15m" in md
    assert "`project-c` · task-runner — 2h00m" in md
    assert "`project-a` · task-runner — 15m" in md


# ── daily_rows (last 7 days table) ──────────────────────────────────────────

def test_render_daily_rows_table():
    rows = [
        (datetime(2026, 1, 15, tzinfo=timezone.utc), {"Client A": 3600}, 3600.0, 0.0),
        (datetime(2026, 1, 14, tzinfo=timezone.utc), {"Client B": 1800},   1800.0, 600.0),
    ]
    md = render_markdown(DAY, states={}, engagement={}, autonomous={}, daily_rows=rows)
    assert "## Последние 7 дней" in md
    assert "| День | Работа | Прочее | Топ проектов |" in md
    # Top project string includes umbrella + hours
    assert "Client A 1h00m" in md
    assert "Client B 30m" in md


def test_portfolio_reconciliation_uses_explicit_targets_and_combined_groups():
    rows = [
        (
            DAY,
            {
                    "Client A": 900.0,
                    "Client A Support": 600.0,
                    "Client B": 300.0,
                    "Client B Ops": 300.0,
                    "Internal": 900.0,
            },
            3000.0,
            0.0,
        ),
    ]

    result = {
        name: (seconds, actual, target, delta)
        for name, seconds, actual, target, delta
        in aggregate.portfolio_reconciliation(
            rows,
            targets={"Client A Total": 0.4, "Client B Total": 0.3},
        )
    }

    groups = {
        "Client A": "Client A Total",
        "Client A Support": "Client A Total",
        "Client B": "Client B Total",
        "Client B Ops": "Client B Total",
    }
    result = {
        name: (seconds, actual, target, delta)
        for name, seconds, actual, target, delta
        in aggregate.portfolio_reconciliation(
            rows,
            targets={"Client A Total": 0.4, "Client B Total": 0.3},
            groups=groups,
        )
    }

    assert result["Client A Total"] == pytest.approx(
        (1500.0, 0.5, 0.4, 0.1)
    )
    assert result["Client B Total"] == pytest.approx(
        (600.0, 0.2, 0.3, -0.1)
    )
    assert result["Internal"] == pytest.approx((900.0, 0.3, 0.0, 0.3))


def test_render_daily_rows_uses_report_dates_not_local_timezone(monkeypatch):
    if not hasattr(time, "tzset"):
        pytest.skip("tzset is not available on this platform")

    old_tz = os.environ.get("TZ")
    monkeypatch.setenv("TZ", "America/Los_Angeles")
    time.tzset()
    try:
        rows = [
            (datetime(2026, 1, 15, 0, 0, 0, tzinfo=timezone.utc), {"Client A": 3600}, 3600.0, 0.0),
        ]
        md = render_markdown(DAY, states={}, engagement={}, autonomous={}, daily_rows=rows)
    finally:
        if old_tz is None:
            monkeypatch.delenv("TZ", raising=False)
        else:
            monkeypatch.setenv("TZ", old_tz)
        time.tzset()

    assert "| Чт 15 янв | 1h00m | 0m | Client A 1h00m |" in md
    assert "| Ср 14 янв |" not in md


# ── «день не закрыт» (issue #15) ────────────────────────────────────────────

# UTC noon of the report day: half the day's window still ahead.
MIDDAY = datetime(2026, 1, 15, 12, 0, 0, tzinfo=timezone.utc)
# One second past the day's UTC window — nothing more can land in it.
AFTER_CLOSE = datetime(2026, 1, 16, 0, 0, 1, tzinfo=timezone.utc)


def test_day_completeness_open_before_utc_window_closes():
    is_open, uncovered, window_end = aggregate.day_completeness(DAY, now=MIDDAY)
    assert is_open
    assert uncovered == pytest.approx(12 * 3600)
    assert window_end == datetime(2026, 1, 16, tzinfo=timezone.utc)


def test_day_completeness_closed_after_utc_window():
    is_open, uncovered, _ = aggregate.day_completeness(DAY, now=AFTER_CLOSE)
    assert not is_open
    assert uncovered == 0.0


def test_day_completeness_closes_exactly_at_the_utc_edge():
    # The boundary itself, not a second past it: `>=` here would mark every
    # fully-elapsed day as open and print "ещё 0m не собрано" on closed reports.
    is_open, uncovered, _ = aggregate.day_completeness(
        DAY, now=datetime(2026, 1, 16, tzinfo=timezone.utc)
    )
    assert not is_open
    assert uncovered == 0.0

    still_open, remaining, _ = aggregate.day_completeness(
        DAY, now=datetime(2026, 1, 15, 23, 59, 59, tzinfo=timezone.utc)
    )
    assert still_open
    assert remaining == pytest.approx(1.0)


def test_day_completeness_treats_naive_now_as_utc():
    is_open, uncovered, _ = aggregate.day_completeness(
        DAY, now=datetime(2026, 1, 15, 12, 0, 0)
    )
    assert is_open
    assert uncovered == pytest.approx(12 * 3600)


def test_render_warns_when_day_not_closed():
    md = render_markdown(DAY, states={}, engagement={}, autonomous={}, now=MIDDAY)
    assert "День не закрыт — данные частичные" in md
    assert "12h00m из 24h суточного окна" in md
    assert "ещё 12h00m не собрано" in md
    # The warning must precede the numbers it qualifies.
    assert md.index("День не закрыт") < md.index("## Как читать")


def test_render_warning_never_promises_more_than_a_day(m_wallclock):
    # `--date` set to a future day: the window has not even started, so raw
    # uncovered time exceeds 24h. The notice must still add up to one day.
    md = render_markdown(
        DAY, states={}, engagement={}, autonomous={},
        umbrella_today={"coding": {}, "other": {}},
        now=datetime(2026, 1, 13, tzinfo=timezone.utc),
    )
    assert "0m из 24h суточного окна" in md
    assert "ещё 24h00m не собрано" in md


def test_render_no_warning_for_closed_day():
    md = render_markdown(DAY, states={}, engagement={}, autonomous={}, now=AFTER_CLOSE)
    assert "День не закрыт — данные частичные" not in md
    assert "⏳ |" not in md  # no day-row carries the open marker


def test_render_marks_open_day_in_daily_table():
    rows = [
        (datetime(2026, 1, 14, tzinfo=timezone.utc), {"Client B": 1800}, 1800.0, 0.0),
        (DAY, {"Client A": 3600}, 3600.0, 0.0),
    ]
    md = render_markdown(
        DAY, states={}, engagement={}, autonomous={}, daily_rows=rows, now=MIDDAY
    )
    assert "| Чт 15 янв ⏳ |" in md
    assert "| Ср 14 янв |" in md  # yesterday's window has closed → no marker
    assert "_⏳ — день не закрыт" in md


def test_render_daily_table_unmarked_when_all_days_closed():
    rows = [(DAY, {"Client A": 3600}, 3600.0, 0.0)]
    md = render_markdown(
        DAY, states={}, engagement={}, autonomous={}, daily_rows=rows, now=AFTER_CLOSE
    )
    assert "| Чт 15 янв | 1h00m |" in md
    assert "⏳ |" not in md
    assert "_⏳ — день не закрыт" not in md


def test_render_signature_carries_snapshot_date():
    # Re-reading yesterday's file must reveal *when* the snapshot was taken,
    # not just the time of day.
    md = render_markdown(DAY, states={}, engagement={}, autonomous={}, now=AFTER_CLOSE)
    assert "2026-01-1" in md.split("_Generated by")[1].split("._")[0]
